--------------------------------------------------------
--  Fichier créé - mercredi-février-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_AGENCE
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SEQ_AGENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMPTECREDIT
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SEQ_COMPTECREDIT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMPTEEPARGNE
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SEQ_COMPTEEPARGNE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DOCUMENT
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SEQ_DOCUMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NOTIFICATION
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SEQ_NOTIFICATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_OBJECTIFEPARGNE
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SEQ_OBJECTIFEPARGNE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TRANSACTIONCREDIT
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SEQ_TRANSACTIONCREDIT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TRANSACTIONEPARGNE
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SEQ_TRANSACTIONEPARGNE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_UTILISATEUR
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SEQ_UTILISATEUR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SESSIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##CEM"."SESSIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AGENCE
--------------------------------------------------------

  CREATE TABLE "C##CEM"."AGENCE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"LATITUDE" FLOAT(126), 
	"LONGITUDE" FLOAT(126), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"FAX" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPTECREDIT
--------------------------------------------------------

  CREATE TABLE "C##CEM"."COMPTECREDIT" 
   (	"ID" NUMBER, 
	"UTILISATEUR_ID" NUMBER, 
	"NUMEROCREDIT" VARCHAR2(50 BYTE), 
	"TYPECREDIT" VARCHAR2(50 BYTE), 
	"MONTANTINITIAL" NUMBER(15,2), 
	"TAUXINTERET" NUMBER(5,2), 
	"DUREEMOIS" NUMBER, 
	"MONTANTMENSUEL" NUMBER(15,2), 
	"DATEDEBUT" TIMESTAMP (6), 
	"DATEFIN" TIMESTAMP (6), 
	"STATUT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPTEEPARGNE
--------------------------------------------------------

  CREATE TABLE "C##CEM"."COMPTEEPARGNE" 
   (	"ID" NUMBER, 
	"UTILISATEUR_ID" NUMBER, 
	"NUMEROCOMPTE" VARCHAR2(50 BYTE), 
	"TYPECOMPTE" VARCHAR2(50 BYTE), 
	"SOLDE" NUMBER(15,2), 
	"TAUXINTERET" NUMBER(5,2), 
	"DATEOUVERTURE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "C##CEM"."NOTIFICATION" 
   (	"ID" NUMBER, 
	"UTILISATEUR_ID" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"CONTENU" VARCHAR2(4000 BYTE), 
	"DATEENVOI" TIMESTAMP (6), 
	"STATUT" VARCHAR2(50 BYTE), 
	"LU" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBJECTIFEPARGNE
--------------------------------------------------------

  CREATE TABLE "C##CEM"."OBJECTIFEPARGNE" 
   (	"ID" NUMBER, 
	"COMPTE_EPARGNE_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"MONTANTCIBLE" NUMBER(15,2), 
	"DATEOBJECTIF" TIMESTAMP (6), 
	"STATUT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SESSIONS
--------------------------------------------------------

  CREATE TABLE "C##CEM"."SESSIONS" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER, 
	"TOKEN" VARCHAR2(500 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"EXPIRED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONCREDIT
--------------------------------------------------------

  CREATE TABLE "C##CEM"."TRANSACTIONCREDIT" 
   (	"ID" NUMBER, 
	"COMPTE_CREDIT_ID" NUMBER, 
	"MONTANT" NUMBER(15,2), 
	"DATEECHEANCE" TIMESTAMP (6), 
	"DATEPAIEMENT" TIMESTAMP (6), 
	"PENALITES" NUMBER(15,2), 
	"STATUT" VARCHAR2(50 BYTE), 
	"REFERENCEPAIEMENT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONEPARGNE
--------------------------------------------------------

  CREATE TABLE "C##CEM"."TRANSACTIONEPARGNE" 
   (	"ID" NUMBER, 
	"COMPTE_EPARGNE_ID" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"MONTANT" NUMBER(15,2), 
	"DATETRANSACTION" TIMESTAMP (6), 
	"MODEOPERATION" VARCHAR2(50 BYTE), 
	"STATUT" VARCHAR2(50 BYTE), 
	"REFERENCE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "C##CEM"."UTILISATEUR" 
   (	"ID" NUMBER, 
	"TYPEUTILISATEUR" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"DATECREATION" TIMESTAMP (6), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##CEM.AGENCE
SET DEFINE OFF;
REM INSERTING into C##CEM.COMPTECREDIT
SET DEFINE OFF;
Insert into C##CEM.COMPTECREDIT (ID,UTILISATEUR_ID,NUMEROCREDIT,TYPECREDIT,MONTANTINITIAL,TAUXINTERET,DUREEMOIS,MONTANTMENSUEL,DATEDEBUT,DATEFIN,STATUT) values ('1','2','0001','Scolaire','750000','11,6','24','20000',null,null,'True');
Insert into C##CEM.COMPTECREDIT (ID,UTILISATEUR_ID,NUMEROCREDIT,TYPECREDIT,MONTANTINITIAL,TAUXINTERET,DUREEMOIS,MONTANTMENSUEL,DATEDEBUT,DATEFIN,STATUT) values ('2','3','0002','Voiture','25000000','15,7','44','1500000',null,null,'True');
REM INSERTING into C##CEM.COMPTEEPARGNE
SET DEFINE OFF;
Insert into C##CEM.COMPTEEPARGNE (ID,UTILISATEUR_ID,NUMEROCOMPTE,TYPECOMPTE,SOLDE,TAUXINTERET,DATEOUVERTURE) values ('1','2','0001','Tsinjo','20000000','2,55',null);
Insert into C##CEM.COMPTEEPARGNE (ID,UTILISATEUR_ID,NUMEROCOMPTE,TYPECOMPTE,SOLDE,TAUXINTERET,DATEOUVERTURE) values ('2','3','0002','Retraite','8000000','5,22',null);
REM INSERTING into C##CEM.NOTIFICATION
SET DEFINE OFF;
REM INSERTING into C##CEM.OBJECTIFEPARGNE
SET DEFINE OFF;
Insert into C##CEM.OBJECTIFEPARGNE (ID,COMPTE_EPARGNE_ID,DESCRIPTION,MONTANTCIBLE,DATEOBJECTIF,STATUT) values ('1','1','Assurance','100000000',null,'False');
Insert into C##CEM.OBJECTIFEPARGNE (ID,COMPTE_EPARGNE_ID,DESCRIPTION,MONTANTCIBLE,DATEOBJECTIF,STATUT) values ('2','2','Assurance','25000000',null,'False');
REM INSERTING into C##CEM.SESSIONS
SET DEFINE OFF;
Insert into C##CEM.SESSIONS (ID,USER_ID,TOKEN,CREATED_AT,EXPIRED_AT) values ('8','2','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im55YXZvdHNpdG9oYWluYUBnbWFpbC5jb20iLCJuYW1laWQiOiIyIiwibmJmIjoxNzQwNDg5MTM1LCJleHAiOjE3NDA0OTI3MzUsImlhdCI6MTc0MDQ4OTEzNSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI2NSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNjUifQ.2d6OowH7A_aK5Gm-xezhcWdQ8m7YbUQtcxgCpPoo3js',to_timestamp('25/02/25 13:12:15,077764000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('25/02/25 17:12:15,077764000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##CEM.SESSIONS (ID,USER_ID,TOKEN,CREATED_AT,EXPIRED_AT) values ('10','2','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im55YXZvdHNpdG9oYWluYUBnbWFpbC5jb20iLCJuYW1laWQiOiIyIiwibmJmIjoxNzQwNDg5MzY0LCJleHAiOjE3NDA0OTI5NjQsImlhdCI6MTc0MDQ4OTM2NCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI2NSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNjUifQ.SAnIoIZF44TINX5GcDGoasQsScEdUx4hgrtljU47rOI',to_timestamp('25/02/25 13:16:04,968314000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('25/02/25 17:16:04,968314000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##CEM.SESSIONS (ID,USER_ID,TOKEN,CREATED_AT,EXPIRED_AT) values ('2','2','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im55YXZvdHNpdG9oYWluYUBnbWFpbC5jb20iLCJuYW1laWQiOiIyIiwibmJmIjoxNzQwNDg2MTU1LCJleHAiOjE3NDA0ODk3NTUsImlhdCI6MTc0MDQ4NjE1NSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI2NSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNjUifQ.9XuvRiaFEDZL1AYOjGqktMWxQbHWrzkQpHiNVZespoo',to_timestamp('25/02/25 12:22:35,058130000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('25/02/25 16:22:35,058130000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##CEM.SESSIONS (ID,USER_ID,TOKEN,CREATED_AT,EXPIRED_AT) values ('4','2','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im55YXZvdHNpdG9oYWluYUBnbWFpbC5jb20iLCJuYW1laWQiOiIyIiwibmJmIjoxNzQwNDg2MzE0LCJleHAiOjE3NDA0ODk5MTQsImlhdCI6MTc0MDQ4NjMxNCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI2NSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNjUifQ.SXF1Se2W2tNHvGq_vNdizYdCUkEJcgGdMaS6m_OnMe4',to_timestamp('25/02/25 12:25:14,320093000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('25/02/25 15:25:33,383000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##CEM.SESSIONS (ID,USER_ID,TOKEN,CREATED_AT,EXPIRED_AT) values ('6','3','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im55ZmlzYW5kcmF0YW5hQGdtYWlsLmNvbSIsIm5hbWVpZCI6IjMiLCJuYmYiOjE3NDA0ODg1NzgsImV4cCI6MTc0MDQ5MjE3OCwiaWF0IjoxNzQwNDg4NTc4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjY1IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI2NSJ9.L5lFtSRSJAa3-thQpI1xYj_U2F8XLqNX2Ey4j0zhhcI',to_timestamp('25/02/25 13:02:58,595768000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('25/02/25 17:02:58,595768000','DD/MM/RR HH24:MI:SSXFF'));
Insert into C##CEM.SESSIONS (ID,USER_ID,TOKEN,CREATED_AT,EXPIRED_AT) values ('12','2','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im55YXZvdHNpdG9oYWluYUBnbWFpbC5jb20iLCJuYW1laWQiOiIyIiwibmJmIjoxNzQwNDg5NjY1LCJleHAiOjE3NDA0OTMyNjUsImlhdCI6MTc0MDQ4OTY2NSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI2NSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNjUifQ.4iVBg4sdcpRLsTyzhy2ufKE9rBlLqyzPVSAjWBIi-LA',to_timestamp('25/02/25 13:21:05,270743000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('25/02/25 17:21:05,270744000','DD/MM/RR HH24:MI:SSXFF'));
REM INSERTING into C##CEM.TRANSACTIONCREDIT
SET DEFINE OFF;
Insert into C##CEM.TRANSACTIONCREDIT (ID,COMPTE_CREDIT_ID,MONTANT,DATEECHEANCE,DATEPAIEMENT,PENALITES,STATUT,REFERENCEPAIEMENT) values ('1','1','20000',null,null,'0','True','CR0001');
Insert into C##CEM.TRANSACTIONCREDIT (ID,COMPTE_CREDIT_ID,MONTANT,DATEECHEANCE,DATEPAIEMENT,PENALITES,STATUT,REFERENCEPAIEMENT) values ('2','2','1500000',null,null,'0','True','CR0002');
REM INSERTING into C##CEM.TRANSACTIONEPARGNE
SET DEFINE OFF;
Insert into C##CEM.TRANSACTIONEPARGNE (ID,COMPTE_EPARGNE_ID,TYPE,MONTANT,DATETRANSACTION,MODEOPERATION,STATUT,REFERENCE) values ('1','1','Depot','2000000',null,'Espece','True','EP0001');
Insert into C##CEM.TRANSACTIONEPARGNE (ID,COMPTE_EPARGNE_ID,TYPE,MONTANT,DATETRANSACTION,MODEOPERATION,STATUT,REFERENCE) values ('2','2','Depot','50000',null,'Espece','True','EP0002');
REM INSERTING into C##CEM.UTILISATEUR
SET DEFINE OFF;
Insert into C##CEM.UTILISATEUR (ID,TYPEUTILISATEUR,NOM,PRENOM,EMAIL,TELEPHONE,ADRESSE,DATECREATION,PASSWORD) values ('2','Client','Tsito
','Kely','nyavotsitohaina@gmail.com','0324463975','Tana',to_timestamp('25/02/25 16:02:20,327000000','DD/MM/RR HH24:MI:SSXFF'),'$2a$11$VCYRfIIVsGTeihthnO9Amut68tiVtnb3CRu2.T0g7W1Z3k6IhFLCu');
Insert into C##CEM.UTILISATEUR (ID,TYPEUTILISATEUR,NOM,PRENOM,EMAIL,TELEPHONE,ADRESSE,DATECREATION,PASSWORD) values ('1','Administrateur','Ny','Fisandratana','nyfisandratana@gmail.com','0336731041','Tana',to_timestamp('26/02/25 12:45:10,819000000','DD/MM/RR HH24:MI:SSXFF'),'$2a$11$98OyIvZXkMcLkhO1p8K8KuVuiBj/zN3EW5nwWWjEaShBnX/M5LTae');
Insert into C##CEM.UTILISATEUR (ID,TYPEUTILISATEUR,NOM,PRENOM,EMAIL,TELEPHONE,ADRESSE,DATECREATION,PASSWORD) values ('3','Client','Rakoto','Noel','rekynpatrick31@gmail.com','0336731041','Tana',to_timestamp('25/02/25 16:02:20,327000000','DD/MM/RR HH24:MI:SSXFF'),'$2a$11$Qs.De9vbcX7uyCzdrEa5NeQuZtt1xt/XpEt4Ktx6jdYsWXMv4FsJG');
--------------------------------------------------------
--  DDL for Trigger SESSIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##CEM"."SESSIONS_TRG" 
BEFORE INSERT ON SESSIONS
FOR EACH ROW
BEGIN
    :NEW.ID := SESSIONS_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##CEM"."SESSIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_AGENCE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##CEM"."TRG_AGENCE" 
BEFORE INSERT ON Agence
FOR EACH ROW
BEGIN
    :NEW.id := seq_agence.NEXTVAL;
END;

/
ALTER TRIGGER "C##CEM"."TRG_AGENCE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_COMPTECREDIT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##CEM"."TRG_COMPTECREDIT" 
BEFORE INSERT ON CompteCredit
FOR EACH ROW
BEGIN
    :NEW.id := seq_comptecredit.NEXTVAL;
END;

/
ALTER TRIGGER "C##CEM"."TRG_COMPTECREDIT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_COMPTEEPARGNE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##CEM"."TRG_COMPTEEPARGNE" 
BEFORE INSERT ON CompteEpargne
FOR EACH ROW
BEGIN
    :NEW.id := seq_compteepargne.NEXTVAL;
END;

/
ALTER TRIGGER "C##CEM"."TRG_COMPTEEPARGNE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_NOTIFICATION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##CEM"."TRG_NOTIFICATION" 
BEFORE INSERT ON Notification
FOR EACH ROW
BEGIN
    :NEW.id := seq_notification.NEXTVAL;
END;

/
ALTER TRIGGER "C##CEM"."TRG_NOTIFICATION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_OBJECTIFEPARGNE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##CEM"."TRG_OBJECTIFEPARGNE" 
BEFORE INSERT ON ObjectifEpargne
FOR EACH ROW
BEGIN
    :NEW.id := seq_objectifepargne.NEXTVAL;
END;

/
ALTER TRIGGER "C##CEM"."TRG_OBJECTIFEPARGNE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TRANSACTIONCREDIT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##CEM"."TRG_TRANSACTIONCREDIT" 
BEFORE INSERT ON TransactionCredit
FOR EACH ROW
BEGIN
    :NEW.id := seq_transactioncredit.NEXTVAL;
END;

/
ALTER TRIGGER "C##CEM"."TRG_TRANSACTIONCREDIT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TRANSACTIONEPARGNE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##CEM"."TRG_TRANSACTIONEPARGNE" 
BEFORE INSERT ON TransactionEpargne
FOR EACH ROW
BEGIN
    :NEW.id := seq_transactionepargne.NEXTVAL;
END;

/
ALTER TRIGGER "C##CEM"."TRG_TRANSACTIONEPARGNE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_UTILISATEUR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##CEM"."TRG_UTILISATEUR" 
BEFORE INSERT ON Utilisateur
FOR EACH ROW
BEGIN
    :NEW.id := seq_utilisateur.NEXTVAL;
END;

/
ALTER TRIGGER "C##CEM"."TRG_UTILISATEUR" ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTIONEPARGNE
--------------------------------------------------------

  ALTER TABLE "C##CEM"."TRANSACTIONEPARGNE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPTEEPARGNE
--------------------------------------------------------

  ALTER TABLE "C##CEM"."COMPTEEPARGNE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SESSIONS
--------------------------------------------------------

  ALTER TABLE "C##CEM"."SESSIONS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CEM"."SESSIONS" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "C##CEM"."SESSIONS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "C##CEM"."SESSIONS" MODIFY ("EXPIRED_AT" NOT NULL ENABLE);
  ALTER TABLE "C##CEM"."SESSIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "C##CEM"."NOTIFICATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AGENCE
--------------------------------------------------------

  ALTER TABLE "C##CEM"."AGENCE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "C##CEM"."UTILISATEUR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPTECREDIT
--------------------------------------------------------

  ALTER TABLE "C##CEM"."COMPTECREDIT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTIONCREDIT
--------------------------------------------------------

  ALTER TABLE "C##CEM"."TRANSACTIONCREDIT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBJECTIFEPARGNE
--------------------------------------------------------

  ALTER TABLE "C##CEM"."OBJECTIFEPARGNE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPTECREDIT
--------------------------------------------------------

  ALTER TABLE "C##CEM"."COMPTECREDIT" ADD CONSTRAINT "FK_COMPTECREDIT_UTILISATEUR" FOREIGN KEY ("UTILISATEUR_ID")
	  REFERENCES "C##CEM"."UTILISATEUR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPTEEPARGNE
--------------------------------------------------------

  ALTER TABLE "C##CEM"."COMPTEEPARGNE" ADD CONSTRAINT "FK_COMPTEEPARGNE_UTILISATEUR" FOREIGN KEY ("UTILISATEUR_ID")
	  REFERENCES "C##CEM"."UTILISATEUR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "C##CEM"."NOTIFICATION" ADD CONSTRAINT "FK_NOTIFICATION_UTILISATEUR" FOREIGN KEY ("UTILISATEUR_ID")
	  REFERENCES "C##CEM"."UTILISATEUR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBJECTIFEPARGNE
--------------------------------------------------------

  ALTER TABLE "C##CEM"."OBJECTIFEPARGNE" ADD CONSTRAINT "FK_OBJECTIF_COMPTEEPARGNE" FOREIGN KEY ("COMPTE_EPARGNE_ID")
	  REFERENCES "C##CEM"."COMPTEEPARGNE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SESSIONS
--------------------------------------------------------

  ALTER TABLE "C##CEM"."SESSIONS" ADD CONSTRAINT "FK_SESSIONS_UTILISATEUR" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##CEM"."UTILISATEUR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONCREDIT
--------------------------------------------------------

  ALTER TABLE "C##CEM"."TRANSACTIONCREDIT" ADD CONSTRAINT "FK_TRANSACTION_COMPTECREDIT" FOREIGN KEY ("COMPTE_CREDIT_ID")
	  REFERENCES "C##CEM"."COMPTECREDIT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONEPARGNE
--------------------------------------------------------

  ALTER TABLE "C##CEM"."TRANSACTIONEPARGNE" ADD CONSTRAINT "FK_TRANSACTION_COMPTEEPARGNE" FOREIGN KEY ("COMPTE_EPARGNE_ID")
	  REFERENCES "C##CEM"."COMPTEEPARGNE" ("ID") ENABLE;
